### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by Sancky** [BigETI/pawn-memory#12]
Hi, if you are still maintaining this repo, I encountered some memory leaks by using your vectors and maps.

**Comment by BigETI** [comment]
Hi, I do. Can you please elaborate, what exactly causes memory leaks?

**Comment by Sancky** [comment]
I think it has something to do with the plugin, I was using some vectors on my server, and is not like i didn't cleared them properly, I'm sure I did, but memory was not removed when a vector was cleared, or sometimes was removed but not instantly, just after some minutes, if i can reproduce it i will send the script here.

**Comment by Sancky** [comment]
![image](https://github.com/BigETI/pawn-memory/assets/54481033/cf5fb248-fcc9-40af-aa7f-40b7ca2c83b5)
so, if I'm doing this, its increasing the memory, but is not clearing it, it remains same like that MAP wasn't even cleared.

**Comment by Sancky** [comment]
As I see, its like that MAP remains the same size (1000) even after clearing the values, same applies for vectors.

**Comment by BigETI** [comment]
That does not seem like, to be an issue of that plugin itself, but rather a library, or usage issue.

**Comment by BigETI** [comment]
Can you please provide a minimal reproducible code, and the methodology used for measurements?

**Comment by Sancky** [comment]
```
public OnGameModeInit() {
    SetTimer("testmap", 10000, false);
    return 1;
}

forward testmap();
public testmap() {
    new Map:map;

    for(new i = 0; i < 1000; ++i) {
        MAP_insert_val_val(map, i, i);
    }

    MAP_clear(map);

    print("called");
}
```

I just tried this script, and its increasing a little bit the memory, but it isn't clearing it as it should.


before that function is called
![image](https://github.com/BigETI/pawn-memory/assets/54481033/45787c2f-6c29-4fb0-a692-0857cde6fea0)

after that function is called
![image](https://github.com/BigETI/pawn-memory/assets/54481033/396121d3-ed10-42c5-80d8-fb805aeb250f)

**Comment by Sancky** [comment]
I didn't use any special method to see memory leaks, just looking at memory

**Comment by BigETI** [comment]
Did you ever encounter `Run time error 3: "Stack/heap collision (insufficient stack size)"` while executing that example? (Try [crashdetect](https://github.com/Zeex/samp-plugin-crashdetect) to catch the real issue)
This problem is not a [pawn-memory](https://github.com/BigETI/pawn-memory) issue, but it is an issue with [pawn-map](https://github.com/BigETI/pawn-map), where too many recursive calls are made, during the map cleanup process, which causes the callback to terminate prematurely.
Therefore it is indeed leaking memory in that example.

I have no idea what the issue with [pawn-vector](https://github.com/BigETI/pawn-vector) is. Please open a ticket at the respective repository, and provide at least a working example, in order to re-produce the associated issue.

Thank you for reporting this issue!
